{% set name = "pytest-mock" %}
{% set version = "3.7.0" %}
{% set hash = "5112bd92cc9f186ee96e1a92efc84969ea494939c3aead39c50f421c4cc69534" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - python
    - pytest >=5.0

test:
  requires:
    - pytest-asyncio
    - pip
    {% if version == "3.7.0" %}- pytest <7{% endif %}

  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    - pytest --help
    - pytest -vv tests

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test
  dev_url: https://github.com/pytest-dev/pytest-mock
  doc_url: https://pytest-mock.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - nicoddemus
