{% set name = "pytest-mock" %}
{% set version = "3.15.0" %}
{{ brake to fail build }}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ab896bd190316b9d5d87b277569dfcdf718b2d049a2ccff5f7aca279c002a1cf

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
    - setuptools_scm
    - toml
  run:
    - python
    - pytest >=6.2.5

test:
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --help
    # Note running with -vv will cause the test to fail due to:
    # https://github.com/pytest-dev/pytest-mock/issues/534
    - pytest tests
  requires:
    - pytest-asyncio
    - pip

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test
  description: |
    Thin-wrapper around the mock package for easier use with py.test
  dev_url: https://github.com/pytest-dev/pytest-mock
  doc_url: https://pytest-mock.readthedocs.io

extra:
  recipe-maintainers:
    - nicoddemus
