{% set name = "pytest-mock" %}
{% set version = "3.15.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 1849a238f6f396da19762269de72cb1814ab44416fa73a8686deac10b0d87a0f

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
    - toml
  run:
    - python
    - pytest >=6.2.5

test:
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --help
    # Note running with -vv will cause the test to fail due to:
    # https://github.com/pytest-dev/pytest-mock/issues/534
    - pytest tests
  requires:
    - pytest-asyncio
    - pip

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test
  description: |
    Thin-wrapper around the mock package for easier use with py.test
  dev_url: https://github.com/pytest-dev/pytest-mock
  doc_url: https://pytest-mock.readthedocs.io

extra:
  recipe-maintainers:
    - nicoddemus
