{% set name = "pytest-mock" %}
{% set version = "1.4.0" %}
{% set hash_type = "sha256" %}
{% set hash = "23703de886a33b337129867c8befccfdace22d7a49b0a9b17cf937492591a7d2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-mock/pytest-mock-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest
    - mock  # [py26 or py27]

test:
  imports:
    - pytest_mock

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus