{% set name = "pytest-mock" %}
{% set version = "3.16.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 5a8395528b8f498205f3718f575228d0edaed7425fff638f87d1a6c3e0383636

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
    - toml
  run:
    - python
    - pytest >=6.2.5

test:
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --help
    - pytest -vv tests
  requires:
    - pytest-asyncio
    - pip

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test
  description: |
    Thin-wrapper around the mock package for easier use with py.test
  dev_url: https://github.com/pytest-dev/pytest-mock
  doc_url: https://pytest-mock.readthedocs.io

extra:
  recipe-maintainers:
    - nicoddemus
