{% set name = "pytest-mock" %}
{% set version = "1.3.0" %}
{% set hash_type = "sha256" %}
{% set hash = "877104d4bbbc4ad266522b7cebc9b11a2c7ec9ce15c43ad6b1ab78aced293989" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/p/pytest-mock/pytest-mock-{{ version }}.zip
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pytest
    - setuptools
  run:
    - python
    - pytest
    - mock  # [py26 or py27]

test:
  imports:
    - pytest_mock

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus