{% set name = "pytest-mock" %}
{% set version = "3.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-mock/pytest_mock-3.15.0.tar.gz
  sha256: ab896bd190316b9d5d87b277569dfcdf718b2d049a2ccff5f7aca279c002a1cf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - setuptools-scm
  run:
    - python
    - pytest >=6.2.5

test:
  requires:
    - pytest-asyncio
    - pip
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    # check that pip gets the correct version
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --help
    - pytest -vv tests

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test
  description: |
    Thin-wrapper around the mock package for easier use with py.test
  dev_url: https://github.com/pytest-dev/pytest-mock
  doc_url: https://pytest-mock.readthedocs.io

extra:
  recipe-maintainers:
    - nicoddemus
