{% set name = "pytest-mock" %}
{% set version = "3.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2719255a1efeceadbc056d6bf3df3d1c5015530fb40cf347c0f9afac88410bd0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - python
    - pytest >=6.2.5

test:
  requires:
    - pytest-asyncio
    - pip
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    # check that pip gets the correct version 
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --help
    - pytest -vv tests

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test
  description: |
    Thin-wrapper around the mock package for easier use with py.test
  dev_url: https://github.com/pytest-dev/pytest-mock
  doc_url: https://pytest-mock.readthedocs.io

extra:
  recipe-maintainers:
    - nicoddemus
