{% set name = "pytest-mock" %}
{% set version = "1.6.3" %}
{% set hash_type = "sha256" %}
{% set hash = "920d1167af5c2c2ad3fa0717d0c6c52e97e97810160c15721ac895cac53abb1c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest
    - mock  # [py26 or py27]

test:
  source_files:
    - test_pytest_mock.py
  imports:
    - pytest_mock
  commands:
    - py.test --help
    - pytest test_pytest_mock.py

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus
