{% set name = "pytest-mock" %}
{% set version = "3.10.0" %}
{% set hash = "fbbdb085ef7c252a326fd8cdcac0aa3b1333d8811f131bdcc701002e1be7ed4f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}
  patches:
    - patches/0001-update-expected-message-to-match.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<37]

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - python
    - pytest >=5.0

test:
  requires:
    - pytest-asyncio
    - pip
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    # check that pip gets the correct version 
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --help
    - pytest -vv tests -k "not test_monkeypatch_ini"

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test
  description: |
    Thin-wrapper around the mock package for easier use with py.test
  dev_url: https://github.com/pytest-dev/pytest-mock
  doc_url: https://pytest-mock.readthedocs.io

extra:
  recipe-maintainers:
    - nicoddemus
