{% set name = "pytest-mock" %}
{% set version = "1.10.2" %}
{% set hash_type = "sha256" %}
{% set hash = "cbec53e7cb0f2b57275220cb4f2822093ac89e486095555105ffe1a4e2f11df4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - pytest
    - mock  # [py27]

test:
  source_files:
    - test_pytest_mock.py
  imports:
    - pytest_mock
  commands:
    - py.test --help
    - pytest test_pytest_mock.py

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus
