travis:
  secure:
    BINSTAR_TOKEN: cWa9/a2SvNHxw+5d8tbS7cpfu/ebipW+JQiILM/EBVNGO6xnfnatZ0CpGtLAOGte2HTw+WeK+8GkHFPJ7HVqmlw4Iqqt8Hj119Lf4+yyScn3FCodjI+59tI5FesZ6PQYdN75cFTZqHbAS3ZSJrWxRTAP9GIj+KYVdcfNHpc7DT60izMQ9AqtzNC3BBZ9lpjFi9arum8DBHBqiMVztONrLSC+AOHSZbbff885NRAKySIMAOs9sI3bKjcCiK0gx1Gb+416UBdOCXWdf0BRIrLqZirWI3MXgvHW91iPbXJuyo2m7X1p4wYEFF2674CsKFicR6fRfHf53lWa2FZkSO106ev3Il9Wj4yo2sCf3pkUWtGtIioROvdJq4gDfKXwhjyOQRtOM4bwVwE+OdFYb2dyZS23EMIsbEXgR1SOcx25F3dvRdEr3NBpqzHWa30JOCk+SONxKhAgmge6IZlXlCDt9ymiPwgXC/HSk2IAsL+AGyo6v3zBGXBoVAQV6LR/uJKF8fpYgD5M981iiTnC6XXtPH1oLEijUcbEvGJiUX3VKHV53mzyBj93T8gdgVR7sxypqDDGTXO9a9H/RU8nUN8ui/s9CfnIQChjQMo4h7bBXoWKFx7q2dITEgxccHcf/hoDSjtjRWf8ZCLM55Q44BWNO8jEIfQxSvT2hcrEQxMTJfc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
