travis:
  secure:
    BINSTAR_TOKEN: Qo8I4kqXYakShMqx+anXGf96lpVky7qJZqs8YPoRAfLVWLquYwB8KODvDw1/LvtUiV0TY2/qSo6fO2CPs9cG/VxP/5aBU1n3TXVvGZ0JTImIsZdNZlUw82kYzkS6EBAFyP3l9DdgXMKf9PA/51BBIOVpnn3+9vj4dxaDsgCZTfQGjDybQQftRNCpVq3vcYR/qsiBUanw5HKn/+jzPeRpWuFgwSgULOzDVRHWG1JPH4e4sLXevX4ng9uhdDfTXDg6bS2BP9ogPgbVjGIUV8tRqK6rT+URtsGtff8Wtet1Aq/3mv6t1InczDjA7cUsPB2YlFVqYfmzrRvn5zYL8+hhtzXze5Kj+B+zjLDPCAKTzyB+K/jcYlm/7ZwPdB0x14lynsq4XBBn9oAyJ1CotVd4RwrbxB46yZ+tH7KQy7LutW87B091U6PkCDASCapYpAbhXBlwrUGfVwl/j/IZipvWF5i7Q5mvckNHZDbPZXht0zl+ZQYWWeE/CJNT5GNtjhZL03BULmkvbXNgXpeThiXer0h+mof3+/BRO1Xqgm/MdGU0hSeeHpWwHeFnbFk7s7sZHgAmJZjCT5mEhSnYbM41AiyJdNtTfTRqMBaJtz+yt9ri/BAf1raoSoIqmxQaNpqwFTieBGUS6g0vaHhb2DgxlRGyBhBi4yOb7yz9HGwo3Yg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
