appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ovVW7Sdwj4to/gz2xnsUXVdi0pavJkVWT6NWd1J7uGQrqmnfebtRz0vFlccmS3VxERUF276J9WDvTLykFpaq6BcXYXbdBo9cFmT2aFfFsSE0Uk4jdBQN0AeyEllUQ082b0tzdHGV4YkDaP6AadmyL5ZUZVTnHH6LZRZPzSSZcAQXEsCNSpoFhdVku8ZLE4/+v1orjS/BxBuTa8E1YD6sR331/PhdEH+Ei3dTLnjzi1r81CHlAJUiU2Oq976OJHQGmCqB3PWvkBdtPsCEQ5OsuY6ZXmFGFs71pTjv+UnJKhyT5rLuqnAExzrqs9dnwE8KXheEFtO7M1x3AuGL/Bp1F8N+A9Bu+5gniHTUJzHDRpSYe2E9yfXqAxgrCg8nHudw9loX1J7b++hkz6VmTFGymdGWXcVuVCWmxUD48dGdG/o4C0KG6ga3t8+Zw2EeBETR2oVnaagswrPdEhwpevgM+U56trIkRNgi9MY1Rl/uzceS6jKcKCsYRNb+VfY/6wUlYp8wDtCHBsp7YEINHj2A5lXzX/7APzUQPJkoV4+co5MNxnYhIbkl2Frhi2wc7xw8aACHyyQzLnAmJYnNkewO+GxOcNcx7DQmiLom5LTPO5J2/Etw9HD7lkrTZbMo1XUuw0hiK6LtdKOidtL34DwkpDNoIp8Q5+8mI02Yhj96TDE=}
provider:
  win: azure
